sudo: required
services:
  - docker
language: general
script:
  - docker build -f Dockerfile.prod -t quorauk/dashboardelixir .
  - docker run -e CB_PASS -e CB_USER -e GITHUB_API_KEY -e JENKINS_PASS -e JENKINS_USER -e TRELLO_KEY -e TRELLO_TOKEN -it quorauk/dashboardelixir mix test
