FROM elixir:1.5.3-alpine
WORKDIR /app
RUN apk add --update \
      curl \
      inotify-tools \
      bash \
      nodejs
ADD mix.exs /app/mix.exs
ADD mix.lock /app/mix.lock
RUN mix local.hex --force
RUN mix local.rebar --force
ADD . /app
RUN mix compile
CMD ["mix", "phoenix.server"]
